[package]
name = "vulnerable-owner"
version = "0.1.0"
description = "Vulnerable implementation demonstrating missing owner check"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "vulnerable_owner"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"